### ISSUE TITLE
Error Starting DesignActivity

### ISSUE THREAD

**Issue by AlfredGonz** [snaptee/SnapteeSDK-Android-Example#2]
Hello, I am trying to implement the library but I have an error in the step where I open DesignActivity. I get
```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.alfredo.arteka/co.snaptee.sdk.DesignActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2858)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
        at co.snaptee.shared.utils.BitmapHelper.getFilePathFromData(BitmapHelper.java:51)
        at co.snaptee.sdk.DesignActivity.onCreate(DesignActivity.java:130)
        at android.app.Activity.performCreate(Activity.java:6982)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2811)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
```

I already included the file snaptee-sdk.aar without any error and declare the activities in my manifest, I don't know what happened or what  I may be ignoring

**Comment by adi-li** [comment]
@ManuelMartinez96  Can you give us more details about how you open the `DesignActivity`?
e.g. the example code to reproduce the error
